
playerFilesWin = {
  "lib/avcodec-56.dll"    : { "flag_deps" : True, "should_be_removed" : True },
  "lib/avformat-56.dll"   : { "flag_deps" : True, "should_be_removed" : True },
  "lib/avutil-54.dll"     : { "flag_deps" : True, "should_be_removed" : True },
  "lib/swscale-3.dll"     : { "flag_deps" : True, "should_be_removed" : True },
  "lib/gen_files_list.py" : { "flag_deps" : True, "should_be_removed" : True },
  "lib/crashrpt_lang.ini" : { "flag_deps" : True, "should_be_removed" : True },
  "lib/CrashSender.exe"   : { "flag_deps" : True, "should_be_removed" : True },
  "lib/avcodec-57.dll"    : { "flag_deps" : True, "should_be_removed" : True },
  "lib/avformat-57.dll"   : { "flag_deps" : True, "should_be_removed" : True },
  "lib/avutil-55.dll"     : { "flag_deps" : True, "should_be_removed" : True },
  "lib/swscale-4.dll"     : { "flag_deps" : True, "should_be_removed" : True },
  

  "lib/avcodec-58.dll"    : { "flag_deps" : True},
  "lib/avformat-58.dll"   : { "flag_deps" : True},
  "lib/avutil-56.dll"     : { "flag_deps" : True},
  "lib/swscale-5.dll"     : { "flag_deps" : True},

  "lib/cef.pak" : { "flag_deps" : True },
  "lib/cef_100_percent.pak" : { "flag_deps" : True },
  "lib/cef_200_percent.pak" : { "flag_deps" : True },
  "lib/cef_extensions.pak" : { "flag_deps" : True },
  "lib/chrome_elf.dll" : { "flag_deps" : True },
  "lib/d3dcompiler_43.dll" : { "flag_deps" : True },
  "lib/d3dcompiler_47.dll" : { "flag_deps" : True },
  "lib/devtools_resources.pak" : { "flag_deps" : True },
  "lib/icudtl.dat" : { "flag_deps" : True },
  "lib/libcef.dll" : { "flag_deps" : True },
  "lib/libEGL.dll" : { "flag_deps" : True },
  "lib/libGLESv2.dll" : { "flag_deps" : True },
  "lib/libGLESv1_CM.dll" : { "flag_deps" : True },
  "lib/angle_util.dll" : { "flag_deps" : True },
  "lib/natives_blob.bin" : { "flag_deps" : True },
  "lib/snapshot_blob.bin" : { "flag_deps" : True },
  "lib/v8_context_snapshot.bin" : { "flag_deps" : True },
  "lib/widevinecdmadapter.dll" : { "flag_deps" : True, "should_be_removed" : True},
  "lib/images/sample_app.png" : { "flag_deps" : True, "should_be_removed" : True},


  "lib/locales/am.pak" : { "flag_deps" : True },
  "lib/locales/ar.pak" : { "flag_deps" : True },
  "lib/locales/bg.pak" : { "flag_deps" : True },
  "lib/locales/bn.pak" : { "flag_deps" : True },
  "lib/locales/ca.pak" : { "flag_deps" : True },
  "lib/locales/cs.pak" : { "flag_deps" : True },
  "lib/locales/da.pak" : { "flag_deps" : True },
  "lib/locales/de.pak" : { "flag_deps" : True },
  "lib/locales/el.pak" : { "flag_deps" : True },
  "lib/locales/en-GB.pak" : { "flag_deps" : True },
  "lib/locales/en-US.pak" : { "flag_deps" : True },
  "lib/locales/es-419.pak" : { "flag_deps" : True },
  "lib/locales/es.pak" : { "flag_deps" : True },
  "lib/locales/et.pak" : { "flag_deps" : True },
  "lib/locales/fa.pak" : { "flag_deps" : True },
  "lib/locales/fi.pak" : { "flag_deps" : True },
  "lib/locales/fil.pak" : { "flag_deps" : True },
  "lib/locales/fr.pak" : { "flag_deps" : True },
  "lib/locales/gu.pak" : { "flag_deps" : True },
  "lib/locales/he.pak" : { "flag_deps" : True },
  "lib/locales/hi.pak" : { "flag_deps" : True },
  "lib/locales/hr.pak" : { "flag_deps" : True },
  "lib/locales/hu.pak" : { "flag_deps" : True },
  "lib/locales/id.pak" : { "flag_deps" : True },
  "lib/locales/it.pak" : { "flag_deps" : True },
  "lib/locales/ja.pak" : { "flag_deps" : True },
  "lib/locales/kn.pak" : { "flag_deps" : True },
  "lib/locales/ko.pak" : { "flag_deps" : True },
  "lib/locales/lt.pak" : { "flag_deps" : True },
  "lib/locales/lv.pak" : { "flag_deps" : True },
  "lib/locales/ml.pak" : { "flag_deps" : True },
  "lib/locales/mr.pak" : { "flag_deps" : True },
  "lib/locales/ms.pak" : { "flag_deps" : True },
  "lib/locales/nb.pak" : { "flag_deps" : True },
  "lib/locales/nl.pak" : { "flag_deps" : True },
  "lib/locales/pl.pak" : { "flag_deps" : True },
  "lib/locales/pt-BR.pak" : { "flag_deps" : True },
  "lib/locales/pt-PT.pak" : { "flag_deps" : True },
  "lib/locales/ro.pak" : { "flag_deps" : True },
  "lib/locales/ru.pak" : { "flag_deps" : True },
  "lib/locales/sk.pak" : { "flag_deps" : True },
  "lib/locales/sl.pak" : { "flag_deps" : True },
  "lib/locales/sr.pak" : { "flag_deps" : True },
  "lib/locales/sv.pak" : { "flag_deps" : True },
  "lib/locales/sw.pak" : { "flag_deps" : True },
  "lib/locales/ta.pak" : { "flag_deps" : True },
  "lib/locales/te.pak" : { "flag_deps" : True },
  "lib/locales/th.pak" : { "flag_deps" : True },
  "lib/locales/tr.pak" : { "flag_deps" : True },
  "lib/locales/uk.pak" : { "flag_deps" : True },
  "lib/locales/vi.pak" : { "flag_deps" : True },
  "lib/locales/zh-CN.pak" : { "flag_deps" : True },
  "lib/locales/zh-TW.pak" : { "flag_deps" : True },

#      "lib/localhost.pack" : {},

  "lib/u2ec.dll" : { "should_be_removed" : True },

  "lib/collector.dll"   : { "should_be_removed" : True },
  "lib/logging.dll"     : {},  
  "lib/rtspclient.dll"  : { "should_be_removed" : True },
  "lib/crash_reporter.cfg" : {},  
  "lib/benchmark.data"             : { "should_be_removed" : True },
  "lib/background.ts"              : { "should_be_removed" : True },
  "lib/benchmark_fullhd_hi.data"   : {},
  "lib/benchmark_fullhd_low.data"  : { "should_be_removed" : True },
  "lib/benchmark_hdready_hi.data"  : {},
  "lib/benchmark_hdready_low.data" : { "should_be_removed" : True },
  "lib/config.ini" : { "may_be_modified" : True, "may_be_removed" : True },

  "quickreset.exe"           : { "should_be_removed" : True },
  "lib/LiquidSkyHelper.exe"  : { "should_be_removed" : True },
  "lib/lang_en.ini"          : { "should_be_removed" : True },
  "lib/render-cef.dll"       : { "should_be_removed" : True },
  "lib/player-cef.dll"       : { "should_be_removed" : True },
  "lib/render-cuda.dll"      : { "should_be_removed" : True },
  "lib/render-ffmpeg.dll"    : {},
  "lib/render-ffmpeg-hw.dll" : { "should_be_removed" : True},
  
  "lib/usb_driver.exe" : { "should_be_removed" : True },
  
  #default liquidsky version
  
  "LiquidSkyClient.exe" : {},
  "lib/LiquidSky.exe"   : {},
  
  "lib/usb_driver.msi" : { "should_be_removed" : True },
  "lib/UsbHelper.exe" : { "should_be_removed" : True },
  
  "lib/Vivien.exe"   : { "should_be_removed" : True },
  "VivienClient.exe" : { "should_be_removed" : True },
}

#if you add any new file to verizon, please make sure that it is included to main list too
playerFilesWinCast = {
  "lib/usb_driver.msi" : {},
  "lib/UsbHelper.exe" : {},
  
  "lib/Vivien.exe"   : {},
  "VivienClient.exe" : {},
 
  "lib/LiquidSky.exe"   : { "should_be_removed" : True }, 
  "LiquidSkyClient.exe" : { "should_be_removed" : True },
  
  "lib/localhost1.pack" : { "should_be_removed" : True },
  "lib/localhost2.pack" : { "should_be_removed" : True },
  "lib/localhost3.pack" : { "should_be_removed" : True },
  "lib/localhost4.pack" : { "should_be_removed" : True },
  
}

playerFilesMac = {
  "Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework"      : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/am.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ar.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/bg.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/bn.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ca.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/cef.pak"                : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/cef_100_percent.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/cef_200_percent.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/cef_extensions.pak"     : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/cs.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/da.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/de.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/devtools_resources.pak" : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/el.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/en.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/en_GB.lproj/locale.pak" : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/es.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/es_419.lproj/locale.pak": { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/et.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/fa.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/fi.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/fil.lproj/locale.pak"   : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/fr.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/gu.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/he.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/hi.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/hr.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/hu.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/icudtl.dat"             : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/id.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/Info.plist"             : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/it.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ja.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/kn.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ko.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/lt.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/lv.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ml.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/mr.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ms.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/natives_blob.bin"       : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/nb.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/nl.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/pl.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/pt_BR.lproj/locale.pak" : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/pt_PT.lproj/locale.pak" : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ro.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ru.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/sk.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/sl.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/snapshot_blob.bin"      : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/sr.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/sv.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/sw.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/ta.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/te.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/th.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/tr.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/uk.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/vi.lproj/locale.pak"    : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/zh_CN.lproj/locale.pak" : { "access_mode" : "644" },
  "Frameworks/Chromium Embedded Framework.framework/Resources/zh_TW.lproj/locale.pak" : { "access_mode" : "644" },

  "Frameworks/LiquidSky Helper.app/Contents/Info.plist"             : { "access_mode" : "644" },
  "Frameworks/LiquidSky Helper.app/Contents/MacOS/LiquidSky Helper" : { "access_mode" : "755" },

  "Info.plist"                          : { "access_mode" : "644" },

  "MacOS/libavcodec.dylib"              : { "access_mode" : "644" },
  "MacOS/libavformat.dylib"             : { "access_mode" : "644" },
  "MacOS/libavutil.dylib"               : { "access_mode" : "644" },
  "MacOS/libcollector.dylib"            : { "access_mode" : "644", "should_be_removed" : True },
  "MacOS/liblogging.dylib"              : { "access_mode" : "644" },
  "MacOS/libplayer-cef.dylib"           : { "access_mode" : "644" },
  "MacOS/librender-ffmpeg-hw.dylib"     : { "access_mode" : "644" },
  "MacOS/librender-ffmpeg.dylib"        : { "access_mode" : "644" },
  "MacOS/librtspclient.dylib"           : { "access_mode" : "644" },
  "MacOS/libswscale.dylib"              : { "access_mode" : "644" },
  "MacOS/LiquidSky"                     : { "access_mode" : "755", "should_be_removed" : True },
  "MacOS/liquidsky-client"              : { "access_mode" : "755" },
  "Resources/background.ts"             : { "access_mode" : "644", "should_be_removed" : True },
  "Resources/benchmark_fullhd_hi.data"  : { "access_mode" : "644", "should_be_removed" : True },
  "Resources/benchmark_hdready_hi.data" : { "access_mode" : "644", "should_be_removed" : True },
  "Resources/lang_en.ini"               : { "access_mode" : "644" },
  "Resources/liquidsky.icns"            : { "access_mode" : "644" },
  "Resources/localhost.pack"            : { "access_mode" : "644" },
}

streamerFilesWin = {
  "avcodec-57.dll" : { "should_be_removed" : True },
  "avformat-57.dll" : { "should_be_removed" : True },
  "avutil-55.dll" : { "should_be_removed" : True },
  "swscale-4.dll" : { "should_be_removed" : True },
  
  "avcodec-58.dll" : {},
  "avformat-58.dll" : {},
  "avutil-56.dll" : {},
  "swscale-5.dll" : {},
  
  "crashrpt_lang.ini" : {},
  "CrashSender.exe" : {},
  "osk-monitor.exe" : {},
  "osk.exe" : {},
  "sky.cfg" : { "may_be_modified" : True, "may_be_removed" : True },
  "streamer-service.exe" : {},
  "streamer-updater.exe" : { "should_be_removed" : True },
  "update-executor.exe" : {},
  "streamer.exe" : { "should_be_removed" : True },
  "SkyBeam.exe" : {},
  "storagetool.exe" : {},
  "setuptool.exe" : {},
  "vmhelper.dll" : {},
  "logging.dll" : {},
  "changelang.exe" : {},
  "app-sender.exe" : {},
  "process-monitor.exe" : {},
  "webrtc-lib.dll" : {},
  "lsfb.exe" : {},
}

streamerFilesWinCast = {
  "usb-service.exe" : {},
}

branchIniDisabled = {
  "lib/branch.ini" : { "should_be_removed" : True },
}

branchIniEnabled = {
  "lib/branch.ini" : {},
}

targets = {
  "player-win"   : { "files" : playerFilesWin,   "path" : ["buildproject", "player"],                    "brands" : { "cast" : playerFilesWinCast }, },
  "player-mac"   : { "files" : playerFilesMac,   "path" : ["buildproject", "LiquidSky.app", "Contents"], "brands" : {}, },
  "streamer-win" : { "files" : streamerFilesWin, "path" : ["buildproject", "streamer"],                  "brands" : { "cast" : streamerFilesWinCast }, },
}
